In [2]:
import pandas as pd

df = pd.read_parquet('./clus_2010.parquet')
df.head(10)

         Node  Clustering_Coefficient
0  AUS_AGRagr                0.000031
1  AUS_AGRfor                0.000008
2  AUS_AGRfis                0.000003
3  AUS_ENRcoa                0.000010
4  AUS_ENRoil                0.000106
5  AUS_ENRgas                0.000038
6    AUS_MIN+                0.000049
7  AUS_MANfoo                0.000073
8  AUS_MANtex                0.000037
9  AUS_MANwoo                0.000042

In [3]:
import pandas as pd

df = pd.read_parquet('./hub_aut_2010.parquet')
df.head(10)

         node     hub_score  authority_score
0  AUS_AGRagr  1.020394e-05         0.000072
1  AUS_AGRfor  2.857383e-07         0.000004
2  AUS_AGRfis  1.196494e-05         0.000006
3  AUS_ENRcoa  1.080096e-05         0.000017
4  AUS_ENRoil  3.152986e-05         0.000025
5  AUS_ENRgas  2.865415e-06         0.000020
6    AUS_MIN+  5.800192e-05         0.000071
7  AUS_MANfoo  4.620823e-05         0.000025
8  AUS_MANtex  1.503856e-06         0.000003
9  AUS_MANwoo  3.235448e-06         0.000003

In [4]:
import pandas as pd

df = pd.read_parquet('./dfz_s_2010_bc.parquet')
df.head(10)

            betweenness
AUS_AGRagr     0.000008
AUS_AGRfor     0.000000
AUS_AGRfis     0.000000
AUS_ENRcoa     0.000541
AUS_ENRoil     0.000474
AUS_ENRgas     0.001636
AUS_MIN+       0.019871
AUS_MANfoo     0.000970
AUS_MANtex     0.000000
AUS_MANwoo     0.000485

In [5]:
df = pd.read_parquet('./dfz_2017_c.parquet')
print(df.shape)
print(df.head())

(43, 43)
              AUS           AUT           BEL           BGR           BRA  \
AUS  1.084149e+09  6.238420e+04  5.747700e+05  9.905328e+03  1.893622e+06
AUT  6.674362e+05  2.780530e+08  2.006101e+06  7.359804e+05  7.487210e+05
BEL  8.375578e+05  2.475321e+06  3.590597e+08  3.613359e+05  1.228699e+06
BGR  2.668536e+04  5.598776e+05  1.099716e+06  4.280134e+07  2.973408e+04
BRA  3.523877e+05  2.678348e+05  1.676543e+06  1.442409e+04  1.285324e+09

              CAN           CHE           CHN            CYP           CZE  \
AUS  9.990339e+05  3.682023e+05  1.050325e+08    6648.742606  1.049946e+05
AUT  1.012196e+06  7.543935e+06  6.281719e+06  157774.348386  4.333509e+06
BEL  1.476826e+06  7.054321e+06  8.691683e+06  237766.437778  2.701183e+06
BGR  8.336746e+04  2.163178e+05  4.661436e+05  114518.765132  3.345225e+05
BRA  2.884989e+06  1.543517e+06  4.662149e+07   15755.386201  1.315840e+05

     ...           POL           PRT           ROU           RUS  \
AUS  ...  2.767393e+05  2.069727e+04  1.728039e+04  3.689485e+06
AUT  ...  3.611775e+06  3.035866e+05  2.516478e+06  4.084568e+06
BEL  ...  5.029834e+06  1.492606e+06  1.328287e+06  2.568336e+06
BGR  ...  4.574947e+05  6.907828e+04  2.408430e+06  5.403199e+05
BRA  ...  4.623127e+05  1.200062e+06  3.790175e+05  8.048145e+05

              SVK           SVN           SWE           TUR           USA  \
AUS  1.621869e+04  1.322708e+04  6.942605e+05  1.684791e+06  6.668462e+06
AUT  2.477097e+06  2.545044e+06  1.559394e+06  1.444917e+06  6.766794e+06
BEL  8.248467e+05  4.745117e+05  4.841066e+06  2.850930e+06  1.798563e+07
BGR  1.132579e+05  1.128838e+05  7.639860e+04  1.597262e+06  5.407834e+05
BRA  5.473078e+04  1.296046e+05  4.415510e+05  8.514403e+05  3.192405e+07

              RoW
AUS  3.307537e+07
AUT  8.854573e+06
BEL  2.328482e+07
BGR  2.550902e+06
BRA  3.113855e+07

[5 rows x 43 columns]

In [ ]:
import pandas as pd

# Read the 2017 country-by-country matrix
df = pd.read_parquet('./dfz_2017_c.parquet')

# For each country (same labels on rows and columns):
#   net_inflow = sum of its column (inflows) – sum of its row (outflows)
net = df.sum(axis=0) - df.sum(axis=1)

# Convert to trillions of dollars
net_trillions = net 

# Sort descending
net_trillions = net_trillions.sort_values(ascending=False)

# Print results
print("Net inflow (column – row) in trillion USD, 2017:\n")
for country, value in net_trillions.items():
    print(f"{country}: {value:.3f} T$")

Net inflow (column – row) in trillion USD, 2017:

CHN: 0.000 T$
USA: 0.000 T$
FRA: 0.000 T$
IND: 0.000 T$
TUR: 0.000 T$
MEX: 0.000 T$
ITA: 0.000 T$
IRL: 0.000 T$
CZE: 0.000 T$
HUN: 0.000 T$
ROU: 0.000 T$
PRT: 0.000 T$
BEL: 0.000 T$
SVK: 0.000 T$
HRV: 0.000 T$
LUX: 0.000 T$
GRC: 0.000 T$
MLT: 0.000 T$
ESP: 0.000 T$
POL: 0.000 T$
CYP: 0.000 T$
FIN: 0.000 T$
EST: 0.000 T$
DNK: 0.000 T$
SVN: 0.000 T$
BGR: 0.000 T$
LTU: -0.000 T$
LVA: -0.000 T$
KOR: -0.000 T$
NLD: -0.000 T$
AUT: -0.000 T$
SWE: -0.000 T$
JPN: -0.000 T$
CHE: -0.000 T$
IDN: -0.000 T$
GBR: -0.000 T$
CAN: -0.000 T$
BRA: -0.000 T$
NOR: -0.000 T$
AUS: -0.000 T$
DEU: -0.000 T$
RUS: -0.000 T$
RoW: -0.000 T$

In [6]:
df = pd.read_parquet('./dfz_2017.parquet')
print(df.shape)
print(df.head())

(2063, 2063)
              AUS_AGRagr    AUS_AGRfor     AUS_AGRfis     AUS_ENRcoa  \
AUS_AGRagr  6.658492e+06  6.223187e+02  927944.746478      16.602518
AUS_AGRfor  1.248203e+05  1.678207e+06       0.280594   38079.119811
AUS_AGRfis  5.026101e+05  2.390507e-02  122469.177850    7095.050576
AUS_ENRcoa  4.408497e+02  1.665046e-05       0.000012   65525.706533
AUS_ENRoil  3.669821e+05  2.090681e+05  216803.724605  909299.714866

              AUS_ENRoil    AUS_ENRgas      AUS_MIN+    AUS_MANfoo  \
AUS_AGRagr  5.194398e-02      0.000558  1.296795e+03  2.320730e+07
AUS_AGRfor  1.111552e+04      0.000050  1.345769e+05  3.794293e-05
AUS_AGRfis  2.562512e+03   6332.436629  1.542629e+04  1.807385e+06
AUS_ENRcoa  1.118776e-06      0.000010  6.775896e+04  4.791707e+04
AUS_ENRoil  3.001281e+06  48595.217771  1.660694e+06  7.980062e+04

               AUS_MANtex    AUS_MANwoo  ...   RoW_PROleg     RoW_PUB+  \
AUS_AGRagr  553066.478834  1.153759e-05  ...  4081.428248  8555.681504
AUS_AGRfor       0.000005  1.289067e+06  ...     2.072196     2.004391
AUS_AGRfis   43466.997471  6.696597e+02  ...   531.961285   710.770669
AUS_ENRcoa    7609.368288  6.726880e-03  ...  2468.365896  2857.251106
AUS_ENRoil    4818.686831  1.487011e+04  ...  2632.573329  6243.660970

               RoW_RES+    RoW_TRAair    RoW_TRAinl   RoW_TRApos  \
AUS_AGRagr  2771.951806  59158.375414   6834.973038   605.716444
AUS_AGRfor     0.417375      0.287717      0.188024     0.009122
AUS_AGRfis   252.226395   8029.903406    936.900420    80.511738
AUS_ENRcoa   983.227546   5259.067885  17528.110450   758.359364
AUS_ENRoil  3069.017065  38175.025444  34174.771274  1122.943905

              RoW_TRAwar    RoW_TRDmot   RoW_WATwat   RoW_WATwst
AUS_AGRagr   2242.697256  44346.117854   490.422597   566.222421
AUS_AGRfor      0.367612      9.199512     0.001822     0.007537
AUS_AGRfis    252.468389   3008.613931    12.932246   184.854643
AUS_ENRcoa  72756.791215  34407.752387  1091.413183  1319.568144
AUS_ENRoil  28442.196149  61464.822843  1212.059377   300.669803

[5 rows x 2063 columns]